version: 1.0.{build}

image: Visual Studio 2019

clone_script:

- cmd: >-

    git clone -q --recursive --depth=1 --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%



    git checkout -qf %APPVEYOR_REPO_COMMIT%

build_script:

- cmd: >-

    git config user.email "appveyor@build.bot" && git config user.name "AppVeyor"



    git tag -a -m "AppVeyor build" init



    md build && cd build



    cmake -G"Visual Studio 16 2019" -A x64 -DZYDIS_BUILD_EXAMPLES=OFF -DZYDIS_BUILD_TOOLS=OFF ..



    "%programfiles(x86)%\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\amd64\MsBuild.exe" /nologo /m:2 /p:Configuration=Release /p:Platform="X64" /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" "hzdnptr.sln"



    cd bin\Release\



    7z a hzdnptr.zip injecter.exe patchdll.dll

test: off

artifacts:

- path: build\bin\Release\hzdnptr.zip

  name: hzdnptr.zip